FROM --platform=$BUILDPLATFORM golang:1.22-alpine3.18 AS build
RUN apk add upx
WORKDIR $GOPATH/src/kproximate
COPY . .
ARG TARGETARCH
RUN cd kproximate/controller && GOOS=linux GOARCH=$TARGETARCH go build -v -o /go/bin/kproximate-controller
RUN upx /go/bin/kproximate-controller

# final stage
FROM alpine

RUN adduser \    
    --disabled-password \    
    --gecos "" \    
    --home "/nonexistent" \    
    --shell "/sbin/nologin" \    
    --no-create-home \    
    --uid "1001" \    
    "kproximate"

COPY --from=build /go/bin/kproximate-controller .
USER kproximate:kproximate
ENTRYPOINT ./kproximate-controller